"""U81 — canonical-root severance, fixture-only and safe to run before a ship.

The production repair is deliberately not exercised against the canonical generated
tree here. Every case builds a complete temporary prefix/home/profile fixture instead;
the upstream-healer-shaped materializer is a tiny local executable, never dsh or npm.
"""
from __future__ import annotations

import os
import stat
import subprocess
import sys

import pytest


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SHIP = os.path.join(ROOT, "scripts", "ship.sh")
BUILD = os.path.join(ROOT, "scripts", "build_app.sh")
REPAIR = os.path.join(ROOT, "scripts", "repair_deepseek_profiles.py")
INSTALL = os.path.join(ROOT, "scripts", "install_deepseek.sh")
VENV_REPAIR = os.path.join(ROOT, "scripts", "repair_relocated_venvs.py")


def _prepare_config(root, config, main, binary):
    return subprocess.run(
        ["bash", SHIP, "--prepare-config-fixture", str(root), str(config),
         str(main), str(binary)],
        cwd=ROOT, capture_output=True, text=True, timeout=30,
    )


def test_ship_config_is_derived_atomically_and_recompile_tracks_it(tmp_path):
    root = tmp_path / "canonical root with spaces"
    root.mkdir()
    config = tmp_path / "Config.swift"
    main = tmp_path / "main.swift"
    binary = tmp_path / "Harness"
    main.write_text("main", encoding="utf-8")
    binary.write_text("binary", encoding="utf-8")
    os.utime(main, (10, 10))
    os.utime(binary, (20, 20))  # source is older: only config may request compile.

    config.write_text('let harnessRoot = "/stale/archive"\n', encoding="utf-8")
    changed = _prepare_config(root, config, main, binary)
    assert changed.returncode == 0, changed.stderr + changed.stdout
    assert "config_changed=1 would_recompile=1" in changed.stdout
    assert config.read_text(encoding="utf-8") == (
        "// generated by ship.sh — do not edit\n"
        f'let harnessRoot = "{root}"\n'
        "let fatBuild = true\n"
    )
    first_mtime = config.stat().st_mtime_ns
    # Model swiftc having consumed the generated config during the successful ship.
    binary_mtime = first_mtime + 2_000_000_000
    os.utime(binary, ns=(binary_mtime, binary_mtime))

    unchanged = _prepare_config(root, config, main, binary)
    assert unchanged.returncode == 0, unchanged.stderr + unchanged.stdout
    assert "config_changed=0 would_recompile=0" in unchanged.stdout
    assert config.stat().st_mtime_ns == first_mtime, (
        "an already-correct generated config must keep its mtime so an ordinary ship "
        "does not compile solely because this preparer ran"
    )

    # A prior ship may have generated the correct config before failing upstream of
    # swiftc. Its durable mtime must still make the next ship compile the stale binary.
    os.utime(config, ns=(binary_mtime + 2_000_000_000,
                         binary_mtime + 2_000_000_000))
    durable = _prepare_config(root, config, main, binary)
    assert durable.returncode == 0, durable.stderr + durable.stdout
    assert "config_changed=0 would_recompile=1" in durable.stdout


def test_ship_config_and_build_kind_contracts_remain_explicit():
    ship = open(SHIP, encoding="utf-8").read()
    build = open(BUILD, encoding="utf-8").read()
    assert "cmp -s \"$tmp\" \"$config_path\"" in ship
    assert "mv -f \"$tmp\" \"$config_path\"" in ship
    assert 'let fatBuild = true' in ship
    assert '"$config_changed" -eq 1' in ship
    assert '"$ROOT/app/Config.swift" -nt "$APP/Contents/MacOS/Harness"' in ship
    fixture_exit = 'if [[ "$RESOLVE_FIXTURES" -eq 1 ]]; then'
    production_config = '_prepare_swift_config "$ROOT/app/Config.swift" "$ROOT"'
    assert ship.index(fixture_exit) < ship.index(production_config)
    assert 'let fatBuild = $FATFLAG' in build
    assert "FATFLAG=false" in build and "[[ $FAT -eq 1 ]] && FATFLAG=true" in build
    assert "CFBundleIdentifier local.harness.app" in build
    assert "may be named either" in build and "M.O.T.app" in build


def _fixture(tmp_path, *, stale=False, nested=False, regular=False, backup=False,
             materializer="local"):
    prefix = tmp_path / "prefix"
    prefix_modules = prefix / "node_modules"
    package = prefix_modules / "package"
    package.mkdir(parents=True)
    (package / "owned.txt").write_text("owned", encoding="utf-8")
    boot = prefix_modules / "@deepseek-ai" / "dsh-app-boot" / "lib" / "index.js"
    boot.parent.mkdir(parents=True)
    boot.write_text("fixture boot module", encoding="utf-8")
    anchor = prefix_modules / "@deepseek-ai" / "dsh" / "package.json"
    anchor.parent.mkdir(parents=True)
    anchor.write_text('{"name":"@deepseek-ai/dsh"}', encoding="utf-8")
    home = tmp_path / "home"
    profile = home / "profiles" / "node_modules"
    profile.mkdir(parents=True)
    outside = tmp_path / "archive-target"
    outside.write_text("must not change", encoding="utf-8")
    link_parent = profile / "nested" if nested else profile
    link_parent.mkdir(exist_ok=True)
    target = outside if stale else package
    os.symlink(target, link_parent / "package-link")
    if regular:
        (profile / "unexpected.txt").write_text("do not mutate", encoding="utf-8")
    if backup:
        (profile.parent / "node_modules.u81-backup").mkdir()

    node = tmp_path / "fake-node"
    if materializer == "local":
        body = '''#!/usr/bin/env python3
import os
assert "--input-type=module" in os.sys.argv
assert "--eval" in os.sys.argv
assert "healProfilesModuleFallback" in os.sys.argv[-1]
assert os.path.isfile(os.environ["HARNESS_DSH_BOOT_MODULE"])
assert os.path.isfile(os.environ["HARNESS_DSH_INSTALL_ANCHOR"])
home = os.environ["HARNESS_DSH_PROFILE_HOME"]
prefix = os.environ["FIXTURE_PREFIX"]
tree = os.path.join(home, "profiles", "node_modules")
os.makedirs(os.path.join(tree, "nested"), exist_ok=True)
os.symlink(os.path.join(prefix, "node_modules", "package"), os.path.join(tree, "nested", "package-link"))
print("fixture healer")
'''
    elif materializer == "escape":
        body = '''#!/usr/bin/env python3
import os
home = os.environ["HARNESS_DSH_PROFILE_HOME"]
tree = os.path.join(home, "profiles", "node_modules")
os.makedirs(tree, exist_ok=True)
os.symlink(os.environ["FIXTURE_OUTSIDE"], os.path.join(tree, "escape"))
'''
    elif materializer == "timeout":
        body = "#!/usr/bin/env python3\nimport time\ntime.sleep(10)\n"
    else:
        body = "#!/usr/bin/env python3\nimport sys\nsys.exit(7)\n"
    node.write_text(body, encoding="utf-8")
    node.chmod(0o755)
    return prefix, home, profile, outside, node


def _repair(prefix, home, node, outside, *, timeout=None):
    env = dict(os.environ, FIXTURE_PREFIX=str(prefix), FIXTURE_OUTSIDE=str(outside))
    command = [sys.executable, REPAIR, "--prefix", str(prefix), "--home", str(home),
               "--node", str(node)]
    if timeout is not None:
        command += ["--timeout-seconds", str(timeout)]
    return subprocess.run(
        command,
        cwd=ROOT, env=env, capture_output=True, text=True, timeout=30,
    )


def test_deepseek_profile_repair_noops_for_clean_nested_local_links(tmp_path):
    prefix, home, profile, outside, node = _fixture(tmp_path, nested=True)
    before = os.readlink(profile / "nested" / "package-link")
    result = _repair(prefix, home, node, outside)
    assert result.returncode == 0, result.stderr + result.stdout
    assert "nothing to repair" in result.stdout
    assert os.readlink(profile / "nested" / "package-link") == before
    assert outside.read_text(encoding="utf-8") == "must not change"


def test_deepseek_profile_repair_rebuilds_external_and_dangling_links(tmp_path):
    prefix, home, profile, outside, node = _fixture(tmp_path, stale=True, nested=True)
    result = _repair(prefix, home, node, outside)
    assert result.returncode == 0, result.stderr + result.stdout
    rebuilt = profile / "nested" / "package-link"
    assert rebuilt.is_symlink()
    assert os.path.commonpath((os.path.realpath(rebuilt),
                               os.path.realpath(prefix / "node_modules"))) == \
        os.path.realpath(prefix / "node_modules")
    assert not (profile.parent / "node_modules.u81-backup").exists()
    assert outside.read_text(encoding="utf-8") == "must not change"

    dangling = tmp_path / "dangling"
    os.unlink(rebuilt)
    os.symlink(dangling, rebuilt)
    rerun = _repair(prefix, home, node, outside)
    assert rerun.returncode == 0, rerun.stderr + rerun.stdout
    assert os.path.realpath(profile / "nested" / "package-link").startswith(
        os.path.realpath(prefix / "node_modules") + os.sep
    )

    # A link can name this prefix textually but still be broken; it must rebuild too.
    os.unlink(profile / "nested" / "package-link")
    os.symlink(prefix / "node_modules" / "missing", profile / "nested" / "package-link")
    local_dangling = _repair(prefix, home, node, outside)
    assert local_dangling.returncode == 0, local_dangling.stderr + local_dangling.stdout
    assert os.path.exists(profile / "nested" / "package-link")


def test_deepseek_profile_repair_refuses_regular_entries_and_backup_collision(tmp_path):
    prefix, home, profile, outside, node = _fixture(tmp_path, stale=True, regular=True)
    regular = profile / "unexpected.txt"
    refused = _repair(prefix, home, node, outside)
    assert refused.returncode != 0
    assert regular.read_text(encoding="utf-8") == "do not mutate"
    assert (profile / "package-link").is_symlink()
    assert outside.read_text(encoding="utf-8") == "must not change"

    prefix, home, profile, outside, node = _fixture(tmp_path / "collision", stale=True,
                                                    backup=True)
    collision = _repair(prefix, home, node, outside)
    assert collision.returncode != 0
    assert "backup already exists" in collision.stderr
    assert (profile / "package-link").is_symlink()
    assert outside.read_text(encoding="utf-8") == "must not change"


def test_deepseek_profile_repair_rolls_back_failed_escaping_or_timed_out_materializer(tmp_path):
    for name, materializer in (("failed", "fail"), ("escaping", "escape"),
                               ("timed-out", "timeout")):
        prefix, home, profile, outside, node = _fixture(tmp_path / name, stale=True,
                                                        materializer=materializer)
        original = os.readlink(profile / "package-link")
        result = _repair(prefix, home, node, outside,
                         timeout=0.1 if materializer == "timeout" else None)
        assert result.returncode != 0
        assert os.readlink(profile / "package-link") == original, (
            "the old generated tree must return atomically after an unsuccessful rebuild"
        )
        assert not (profile.parent / "node_modules.u81-backup").exists()
        assert outside.read_text(encoding="utf-8") == "must not change"


def test_installer_calls_the_profile_repair_before_it_claims_success():
    installer = open(INSTALL, encoding="utf-8").read()
    assert "repair_deepseek_profiles.py" in installer
    assert '"$py_repair" "$ROOT/scripts/repair_deepseek_profiles.py"' in installer
    assert '--prefix "$PREFIX" --home "$DSH_HOME_DIR" --node "$node"' in installer
    assert installer.index("repair_deepseek_profiles.py") < installer.index("flip_installed.py")

    repair = open(REPAIR, encoding="utf-8").read()
    assert "healProfilesModuleFallback" in repair
    assert "pathToFileURL" in repair
    assert '"--input-type=module", "--eval", HEALER_PROGRAM' in repair


def _venv_fixture(root, name, package, vendor_dir, *, fail_import=False,
                  binary=False, symlink=False, other_venv=None):
    """Small copied venv with a console script and an editable PEP 660 map."""
    venv = root / "data" / name
    bindir = venv / "bin"
    bindir.mkdir(parents=True)
    (venv / "pyvenv.cfg").write_text("home = /fixture/python", encoding="utf-8")
    old_root = "/archive root with spaces/harness"
    mapped_name = other_venv or name
    console = bindir / "fixture-console"
    console.write_text(f"#!{old_root}/data/{mapped_name}/bin/python\nprint('ok')\n",
                       encoding="utf-8")
    console.chmod(0o751)
    if binary:
        (bindir / "binary-launcher").write_bytes(b"\0not text")
    if symlink:
        os.symlink(console, bindir / "foreign-link")

    module = root / "vendor" / vendor_dir / package
    module.mkdir(parents=True)
    origin = module / "__init__.py"
    origin.write_text("# fixture\n", encoding="utf-8")
    module_stem = root / "vendor" / vendor_dir / "batch_runner.py"
    module_stem.write_text("# fixture module stem\n", encoding="utf-8")
    namespace = root / "vendor" / vendor_dir / "tools" / "wakewords"
    namespace.mkdir(parents=True)
    finder = (venv / "lib" / "python3.11" / "site-packages" /
              f"__editable___{vendor_dir}_finder.py")
    finder.parent.mkdir(parents=True)
    finder.write_text(
        f"MAPPING = {{'{package}': '{old_root}/vendor/{vendor_dir}/{package}', "
        f"'batch_runner': '{old_root}/vendor/{vendor_dir}/batch_runner'}}\n"
        f"NAMESPACES = {{'tools.wakewords': ['{old_root}/vendor/{vendor_dir}/tools/wakewords']}}\n",
        encoding="utf-8")

    python = bindir / "python"
    if fail_import:
        python.write_text("#!/usr/bin/env python3\nimport sys\nsys.exit(9)\n", encoding="utf-8")
    else:
        python.write_text(
            "#!/usr/bin/env python3\nimport os, sys\n"
            f"print({str(origin)!r})\n", encoding="utf-8")
    python.chmod(0o755)
    return venv, console, finder


def _repair_venvs(root):
    return subprocess.run([sys.executable, VENV_REPAIR, "--root", str(root)],
                          cwd=ROOT, capture_output=True, text=True, timeout=30)


def test_relocated_venv_repair_is_narrow_idempotent_and_preserves_mode(tmp_path):
    root = tmp_path / "canonical root with spaces"
    hermes, hermes_console, hermes_finder = _venv_fixture(
        root, "hermes-venv", "hermes_cli", "hermes")
    searx, searx_console, searx_finder = _venv_fixture(
        root, "searxng-venv", "searx", "searxng")
    ignored = root / "data" / "not-a-venv" / "bin"
    ignored.mkdir(parents=True)
    ignored_script = ignored / "old"
    ignored_script.write_text("#!/archive/data/hermes-venv/bin/python\n", encoding="utf-8")
    nested = root / "data" / "nested" / "bridge-venv"
    nested.mkdir(parents=True)
    (nested / "pyvenv.cfg").write_text("ignored", encoding="utf-8")
    bin_cache = hermes / "bin" / "__pycache__"
    bin_cache.mkdir()
    poisoned = bin_cache / "old-root.pyc"
    poisoned.write_text("/archive root with spaces/data/hermes-venv/bin/python\n",
                        encoding="utf-8")
    poisoned_before = poisoned.read_bytes()
    mode = stat.S_IMODE(hermes_console.stat().st_mode)

    result = _repair_venvs(root)
    assert result.returncode == 0, result.stderr + result.stdout
    assert "repaired 4" in result.stdout
    for venv, console, finder in ((hermes, hermes_console, hermes_finder),
                                  (searx, searx_console, searx_finder)):
        assert "/archive root with spaces" not in console.read_text(encoding="utf-8")
        assert str(venv) in console.read_text(encoding="utf-8")
        assert "/archive root with spaces" not in finder.read_text(encoding="utf-8")
        assert str(root / "vendor") in finder.read_text(encoding="utf-8")
    assert str(root / "vendor" / "hermes" / "batch_runner") in \
        hermes_finder.read_text(encoding="utf-8")
    assert stat.S_IMODE(hermes_console.stat().st_mode) == mode
    assert "/archive/data/hermes-venv" in ignored_script.read_text(encoding="utf-8")
    assert poisoned.read_bytes() == poisoned_before

    repaired_bytes = (hermes_console.read_bytes(), hermes_finder.read_bytes(),
                      searx_console.read_bytes(), searx_finder.read_bytes())
    rerun = _repair_venvs(root)
    assert rerun.returncode == 0, rerun.stderr + rerun.stdout
    assert "repaired 0" in rerun.stdout
    assert repaired_bytes == (hermes_console.read_bytes(), hermes_finder.read_bytes(),
                              searx_console.read_bytes(), searx_finder.read_bytes())


@pytest.mark.parametrize("kind", ("binary", "symlink", "other-venv", "fifo"))
def test_relocated_venv_repair_refuses_unsafe_or_ambiguous_console_inputs(tmp_path, kind):
    root = tmp_path / kind
    kwargs = {"binary": kind == "binary", "symlink": kind == "symlink",
              "other_venv": "bridge-venv" if kind == "other-venv" else None}
    _venv, console, finder = _venv_fixture(root, "hermes-venv", "hermes_cli", "hermes",
                                            **kwargs)
    if kind == "fifo":
        os.mkfifo(root / "data" / "hermes-venv" / "bin" / "not-a-console")
    before = (console.read_bytes(), finder.read_bytes())
    result = _repair_venvs(root)
    assert result.returncode != 0
    assert before == (console.read_bytes(), finder.read_bytes())


def test_relocated_venv_repair_refuses_missing_editable_destination_before_writes(tmp_path):
    root = tmp_path / "missing vendor"
    _venv, console, finder = _venv_fixture(root, "hermes-venv", "hermes_cli", "hermes")
    target = root / "vendor" / "hermes"
    for path in (target / "hermes_cli" / "__init__.py", target / "hermes_cli",
                 target / "batch_runner.py", target / "tools" / "wakewords",
                 target / "tools", target):
        if path.exists():
            path.unlink() if path.is_file() else path.rmdir()
    before = (console.read_bytes(), finder.read_bytes())
    result = _repair_venvs(root)
    assert result.returncode != 0
    assert "editable map target is absent" in result.stderr
    assert before == (console.read_bytes(), finder.read_bytes())


def test_relocated_venv_repair_refuses_an_escaping_module_stem_symlink(tmp_path):
    root = tmp_path / "escaping module stem"
    _venv, console, finder = _venv_fixture(root, "hermes-venv", "hermes_cli", "hermes")
    stem = root / "vendor" / "hermes" / "batch_runner.py"
    outside = tmp_path / "outside.py"
    outside.write_text("# outside\n", encoding="utf-8")
    stem.unlink()
    os.symlink(outside, stem)
    before = (console.read_bytes(), finder.read_bytes())
    result = _repair_venvs(root)
    assert result.returncode != 0
    assert "editable map target is absent" in result.stderr
    assert before == (console.read_bytes(), finder.read_bytes())


def test_relocated_venv_repair_refuses_escaping_exact_package_before_py_fallback(tmp_path):
    root = tmp_path / "escaping package before stem"
    _venv, console, finder = _venv_fixture(root, "hermes-venv", "hermes_cli", "hermes")
    package = root / "vendor" / "hermes" / "hermes_cli"
    outside = tmp_path / "outside-package"
    outside.mkdir()
    (outside / "__init__.py").write_text("# outside\n", encoding="utf-8")
    (package / "__init__.py").unlink()
    package.rmdir()
    os.symlink(outside, package)
    (root / "vendor" / "hermes" / "hermes_cli.py").write_text("# in tree stem\n",
                                                                    encoding="utf-8")
    before = (console.read_bytes(), finder.read_bytes())
    result = _repair_venvs(root)
    assert result.returncode != 0
    assert "editable map target is absent" in result.stderr
    assert before == (console.read_bytes(), finder.read_bytes())


def test_relocated_venv_repair_refuses_extensionless_exact_file_before_py_fallback(tmp_path):
    root = tmp_path / "extensionless exact file"
    _venv, console, finder = _venv_fixture(root, "hermes-venv", "hermes_cli", "hermes")
    package = root / "vendor" / "hermes" / "hermes_cli"
    (package / "__init__.py").unlink()
    package.rmdir()
    package.write_text("not a package\n", encoding="utf-8")
    (root / "vendor" / "hermes" / "hermes_cli.py").write_text("# in tree stem\n",
                                                                    encoding="utf-8")
    before = (console.read_bytes(), finder.read_bytes())
    result = _repair_venvs(root)
    assert result.returncode != 0
    assert "editable map target is absent" in result.stderr
    assert before == (console.read_bytes(), finder.read_bytes())


def test_relocated_venv_repair_rolls_back_every_changed_file_after_import_failure(tmp_path):
    root = tmp_path / "rollback"
    _venv, console, finder = _venv_fixture(root, "hermes-venv", "hermes_cli", "hermes",
                                            fail_import=True)
    before = (console.read_bytes(), finder.read_bytes())
    result = _repair_venvs(root)
    assert result.returncode != 0
    assert "import proof failed" in result.stderr
    assert before == (console.read_bytes(), finder.read_bytes())


def test_ship_repairs_repo_before_gate_and_snapshot_after_scripts_copy():
    ship = open(SHIP, encoding="utf-8").read()
    repo_call = '"$VENV_REPAIR_PY" "$ROOT/scripts/repair_relocated_venvs.py" --root "$ROOT"'
    snapshot_call = ('"$VENV_REPAIR_PY" "$DST/scripts/repair_relocated_venvs.py" '
                     '--root "$DST"')
    assert repo_call in ship and snapshot_call in ship
    assert ship.index(repo_call) < ship.index('bash "$ROOT/scripts/verify.sh"')
    assert ship.index('cp -R "$ROOT/$d/." "$DST/$d/"') < ship.index(snapshot_call)
    assert ship.index(snapshot_call) < ship.index('echo "[ship] restarting app + bridge')
