#!/usr/bin/env bash
# Build MOT Deck.app. Flags (combinable, order-independent):
#   --dmg       also package dist/MOT Deck.dmg
#   --portable  bundle a repo seed (source only, no vendor) into the .app so it can
#               self-install on a fresh Mac WITH internet (first-run: main.swift extracts
#               the seed to ~/Library/Application Support/MOT Deck and runs firstrun.sh).
#   --fat       build the FULL offline installer (§G-phase3): bundles uv-standalone CPython
#               + an arm64 wheelhouse + pinned vendor SOURCE + prebuilt Hermes web_dist +
#               the pinned llama-server, so a fresh Mac provisions EVERY component OFFLINE
#               on first run (no PyPI / npm / internet needed for setup). ~2–4 GB.
#               Implies --dmg (the fat app is meant for distribution) and ad-hoc codesign.
# Local build; thin/dev + --dmg + --portable behaviour is UNCHANGED by --fat.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"

DMG=0; PORTABLE=0; FAT=0
for a in "$@"; do case "$a" in
  --dmg) DMG=1 ;;
  --portable) PORTABLE=1 ;;
  --fat) FAT=1 ;;
esac; done
[[ $FAT -eq 1 ]] && DMG=1   # a fat build is a distributable → always produce the dmg

command -v swiftc >/dev/null || {
  echo "swiftc not found. Install Command Line Tools first:  xcode-select --install"; exit 1; }

APP="dist/MOT Deck.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# bake MOT Deck location + build-kind into the binary so the app works from anywhere.
# fatBuild=true routes main.swift to the offline first-run provisioner and resolves the
# runtime root to ~/Library/Application Support/MOT Deck (dev/portable path untouched).
FATFLAG=false; [[ $FAT -eq 1 ]] && FATFLAG=true
cat > app/Config.swift <<EOF
// generated by build_app.sh — do not edit
let motdeckRoot = "$ROOT"
let fatBuild = $FATFLAG
EOF

echo "[motdeck] compiling Swift app..."
swiftc -O app/main.swift app/Config.swift -o "$APP/Contents/MacOS/MOTDeck"

# ── ONE PUBLIC IDENTITY: MOT Deck (U150, Debi 2026-09-07) ─────────────────────
# The M.O.T wordmark remains the artwork. Finder, Dock, menu bar, bundle filename,
# bundle identity and executable use the approved product/machine mapping below.
# A fresh fat install gets it from here; an existing install gets it from ship.sh's
# bundle step (which also writes the localized name — see the long note there on why
# CFBundleDisplayName alone is not reliably honoured when it differs from the filename).
cat > "$APP/Contents/Info.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>MOT Deck</string>
  <key>CFBundleDisplayName</key><string>MOT Deck</string>
  <key>CFBundleIdentifier</key><string>local.motdeck.app</string>
  <key>CFBundleVersion</key><string>0.1</string>
  <key>CFBundleShortVersionString</key><string>0.1</string>
  <key>CFBundleExecutable</key><string>MOTDeck</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSMicrophoneUsageDescription</key><string>MOT Deck uses the microphone for voice dictation into chat.</string>
  <key>NSAppTransportSecurity</key>
  <dict><key>NSAllowsLocalNetworking</key><true/></dict>
</dict></plist>
EOF
mkdir -p "$APP/Contents/Resources/en.lproj"
cat > "$APP/Contents/Resources/en.lproj/InfoPlist.strings" <<'EOF'
CFBundleDisplayName = "MOT Deck";
CFBundleName = "MOT Deck";
EOF

# Preserve the committed per-size M.O.T artwork. It was drawn per resolution because
# resizing the large PNG erases the periods at Dock sizes. Regeneration is only a
# development fallback when the committed artifact is absent.
if [[ -f app/MOTDeck.icns ]]; then
  cp app/MOTDeck.icns "$APP/Contents/Resources/MOTDeck.icns"
  /usr/libexec/PlistBuddy -c "Add :CFBundleIconFile string MOTDeck" "$APP/Contents/Info.plist"
elif [[ -f app/icon.png ]]; then
  echo "[motdeck] building icon..."
  ICONSET=dist/motdeck.iconset; rm -rf "$ICONSET"; mkdir -p "$ICONSET"
  for s in 16 32 64 128 256 512; do
    sips -z $s $s app/icon.png --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
    sips -z $((s*2)) $((s*2)) app/icon.png --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
  done
  iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/MOTDeck.icns" \
    && /usr/libexec/PlistBuddy -c "Add :CFBundleIconFile string MOTDeck" "$APP/Contents/Info.plist" \
    || echo "[motdeck] icon build failed (non-fatal)"
  rm -rf "$ICONSET"
fi

echo "[motdeck] built $APP"

# Phase 2: the panel's artifact renderer needs the self-hosted vendor libs on disk so a
# packaged seed can run offline. Fetch them (idempotent) before either seed is staged.
if [[ $PORTABLE -eq 1 || $FAT -eq 1 ]]; then
  echo "[motdeck] fetching self-hosted panel assets (artifact renderer)…"
  bash scripts/fetch_vendor_assets.sh \
    || { echo "ERROR: fetch_vendor_assets.sh failed — the artifact renderer needs these libs bundled offline."; exit 1; }
fi

if [[ $PORTABLE -eq 1 ]]; then
  echo "[motdeck] bundling portable seed (repo minus .git/.gitmodules/vendor/data/dist)..."
  SEED="$APP/Contents/Resources/motdeck-seed.tar.gz"
  # vendor/ is intentionally excluded — firstrun's bootstrap re-adds the submodules
  # from their PUBLIC upstreams (motdeck.yaml repo/pin), so no private-repo auth is needed.
  # macOS bsdtar otherwise synthesizes AppleDouble `._*` entries for extended
  # attributes. Those bytes do not exist in the staged tree, cannot be owned by the
  # seed manifest, and would make archive contents exceed the manifest's authority.
  COPYFILE_DISABLE=1 tar czf "$SEED" -C "$ROOT" \
    --exclude='./.git' --exclude='./.gitmodules' --exclude='./vendor' \
    --exclude='./data' --exclude='./dist' \
    --exclude='./bridge/tests' --exclude='./bridge/contract_tests' \
    --exclude='./node_modules' --exclude='*/node_modules' \
    --exclude='*/__pycache__' --exclude='*.pyc' --exclude='.DS_Store' \
    .
  echo "[motdeck] seed: $SEED ($(du -h "$SEED" | cut -f1))"
fi

# ─────────────────────────────────────────────────────────────────────────────
# --fat : the full offline installer payload. All heavy lifting is here; guarded so
# a plain/--dmg/--portable build never touches any of it.
# ─────────────────────────────────────────────────────────────────────────────
if [[ $FAT -eq 1 ]]; then
  echo "[motdeck] === FAT build: bundling an offline installer (~2–4 GB) ==="
  command -v uv >/dev/null || { echo "ERROR (fat): uv not found — needed to fetch standalone Python + download wheels. Install:  brew install uv"; exit 1; }

  yaml_build() { awk "/^build:/{f=1} f && /^  $1:/{line=\$0; sub(/#.*/,\"\",line); sub(/^  $1:[[:space:]]*/,\"\",line); gsub(/^[[:space:]]+|[[:space:]]+\$/,\"\",line); gsub(/\"/,\"\",line); print line; exit}" motdeck.yaml; }
  PYVER="$(yaml_build python_version)";  [[ -n "$PYVER" ]]  || { echo "ERROR (fat): build.python_version missing in motdeck.yaml"; exit 1; }
  PYTAG="$(yaml_build python_tag)";      [[ -n "$PYTAG" ]]  || PYTAG="cp312"
  PYSHORT="${PYVER%.*}"   # 3.12.11 -> 3.12 (informational; wheels come from the native standalone interpreter)
  RES="$APP/Contents/Resources"
  WHEELS="$RES/wheelhouse"; mkdir -p "$WHEELS"

  # (1) llama-server must already be installed locally — we bundle the pinned binary.
  if [[ ! -x data/llamacpp/build/bin/llama-server ]]; then
    echo "[motdeck] llama-server not present — installing the pin first..."
    bash scripts/install_llamacpp.sh || { echo "ERROR (fat): install_llamacpp.sh failed — cannot bundle the runner binary."; exit 1; }
  fi

  # (2) Prebuild Hermes web_dist (first-run is offline; no npm on the target).
  if [[ ! -f vendor/hermes/hermes_cli/web_dist/index.html ]]; then
    command -v npm >/dev/null || { echo "ERROR (fat): npm not found and Hermes web_dist is not prebuilt — install Node then re-run (first-run cannot build the dashboard offline)."; exit 1; }
    echo "[motdeck] prebuilding Hermes web dashboard (npm --workspace web)…"
    ( cd vendor/hermes && npm install --workspace web --no-audit --no-fund && npm run build --workspace web )
    [[ -f vendor/hermes/hermes_cli/web_dist/index.html ]] || { echo "ERROR (fat): Hermes web build finished but web_dist/index.html missing."; exit 1; }
  else
    echo "[motdeck] Hermes web_dist already built — reusing."
  fi

  # (3) Bundle uv-managed standalone CPython (relocatable by design).
  echo "[motdeck] fetching standalone CPython $PYVER via uv…"
  uv python install "$PYVER" || { echo "ERROR (fat): 'uv python install $PYVER' failed — pick a version uv can provide (uv python list) and update build.python_version."; exit 1; }
  PYEXE="$(uv python find "$PYVER")" || { echo "ERROR (fat): could not locate the standalone python after install."; exit 1; }
  # install root = two levels above .../bin/python3
  PYROOT="$(cd "$(dirname "$PYEXE")/.." && pwd)"
  [[ -x "$PYROOT/bin/python3" ]] || { echo "ERROR (fat): standalone python layout unexpected at $PYROOT (no bin/python3)."; exit 1; }
  echo "[motdeck] bundling standalone python from $PYROOT"
  tar czf "$RES/python-standalone.tar.gz" -C "$PYROOT" .

  # The bundled standalone interpreter IS the download target — invoking pip through it
  # yields exactly-matching arm64/cp312 wheels for this build Mac (== the target Mac) and
  # correctly resolves sdist-only deps. uv has NO 'pip download' subcommand, so we use the
  # standalone python's own pip. Bootstrap pip into it if the distribution ships without one.
  PYBIN="$PYROOT/bin/python3"
  "$PYBIN" -m pip --version >/dev/null 2>&1 \
    || "$PYBIN" -m ensurepip --upgrade >/dev/null 2>&1 \
    || { echo "ERROR (fat): could not bootstrap pip into the standalone python ($PYBIN) via ensurepip."; exit 1; }

  # (4) WHEELHOUSE — every component's deps as arm64 wheels (+ build backends), OFFLINE source.
  # ⚠️⚠️ RISKIEST STEP: torch/mlx/pydantic-core etc. are large + arch-specific. This only
  # truly verifies on the Mac. We download NATIVELY through the bundled standalone interpreter
  # ("$PYBIN" -m pip download), so wheels match its exact platform (macOS arm64) + tag (cp312)
  # with NO cross-platform flags — and sdist-only deps (pure-python / source-built) resolve too
  # and build on-target from this same wheelhouse (their build backends are downloaded in 4a).
  # (Deliberately NOT using --platform/--only-binary=:all:, which would break sdist-only deps.)
  DL=( "$PYBIN" -m pip download -d "$WHEELS" )
  echo "[motdeck] downloading wheelhouse → $WHEELS (this is large + slow)…"

  # 4a. build backends first (needed for the on-target editable installs of hermes/odysseus/searxng)
  "${DL[@]}" pip setuptools wheel setuptools-scm hatchling hatch-vcs editables \
             pdm-backend poetry-core flit-core scikit-build-core cython pybind11 \
    || { echo "ERROR (fat): build-backend wheel download failed."; exit 1; }
  # 4a.1 some projects pin an OLDER build backend (e.g. hermes needs setuptools>=77,<83).
  # The line above only grabs the newest setuptools, so also bundle an in-range one so the
  # offline build-isolation env for those projects can resolve it. Separate call because a
  # single pip-download resolves ONE version and the two constraints would conflict.
  "${DL[@]}" "setuptools<83,>=77.0" \
    || { echo "ERROR (fat): in-range setuptools (<83) download failed."; exit 1; }

  # 4b. bridge
  "${DL[@]}" -r bridge/requirements.txt || { echo "ERROR (fat): bridge deps download failed."; exit 1; }

  # 4c. odysseus (+ ddgs for Docker-free web search)
  "${DL[@]}" -r vendor/odysseus/requirements.txt ddgs || { echo "ERROR (fat): odysseus deps download failed."; exit 1; }

  # 4d. searxng (source-only project; it has requirements.txt) + its build prereqs
  if [[ -f vendor/searxng/requirements.txt ]]; then
    "${DL[@]}" -r vendor/searxng/requirements.txt pyyaml msgspec typing-extensions pybind11 \
      || { echo "ERROR (fat): searxng deps download failed."; exit 1; }
  else
    echo "[motdeck] WARN (fat): vendor/searxng/requirements.txt not found — cloning searxng source first (scripts/install_searxng.sh clones it)."
    echo "           Run scripts/install_searxng.sh once (or ensure vendor/searxng exists) before a fat build."
    exit 1
  fi

  # 4e. hermes[all] deps — resolve from the local project's pyproject (pip builds metadata,
  #     fetching the backend itself). Downloads runtime deps as wheels/sdists.
  "${DL[@]}" "vendor/hermes[all]" || {
    echo "[motdeck] WARN (fat): 'vendor/hermes[all]' download failed — retrying without the [all] extra.";
    "${DL[@]}" "vendor/hermes" || { echo "ERROR (fat): hermes deps download failed."; exit 1; }; }

  # 4f. MLX runtime (Apple-silicon only; large — torch-free but mlx core is sizeable).
  # PINNED from motdeck.yaml build.mlx_*_pin — the SAME values install_mlx.sh and
  # firstrun_fat.sh install. Unpinned here would bundle whatever is newest while the
  # installers ask for the pinned version → OFFLINE first-run fails on a fresh Mac.
  MLXLM="$(yaml_build mlx_lm_pin)"; MLXVLM="$(yaml_build mlx_vlm_pin)"
  [[ -n "$MLXLM" && -n "$MLXVLM" ]] || { echo "ERROR (fat): build.mlx_lm_pin / build.mlx_vlm_pin missing in motdeck.yaml"; exit 1; }
  echo "[motdeck] mlx pins: mlx-lm==$MLXLM  mlx-vlm==$MLXVLM"
  "${DL[@]}" "mlx-lm==$MLXLM" "mlx-vlm==$MLXVLM" || { echo "ERROR (fat): mlx deps download failed."; exit 1; }

  echo "[motdeck] wheelhouse: $(ls "$WHEELS" | wc -l | tr -d ' ') files, $(du -sh "$WHEELS" | cut -f1)"

  # (5) SEED — pinned vendor SOURCE (incl. prebuilt web_dist) + scripts/bridge/app/config,
  # source-only (strip .git/node_modules/caches). Staged via rsync so we can include
  # vendor/ but drop its heavy/VCS bits, and include ONLY data/llamacpp from data/.
  echo "[motdeck] staging offline seed…"
  STAGE=dist/.fatseed
  rm -rf "$STAGE"; mkdir -p "$STAGE"
  rsync -a \
    --exclude='.git' --exclude='.gitmodules' --exclude='node_modules' \
    --exclude='bridge/tests' --exclude='bridge/contract_tests' \
    --exclude='__pycache__' --exclude='*.pyc' --exclude='.DS_Store' \
    vendor scripts bridge app skills policies motdeck.yaml VERSION "$STAGE/" 2>/dev/null || {
      echo "ERROR (fat): rsync of the seed failed."; exit 1; }
  # ⚠️ VERSION is in that list on purpose (2026-09-02): the seed shipped WITHOUT it for
  # every fat build up to and including the 2026-08-20 dmg, so a freshly provisioned
  # snapshot had no file naming the release it came from — only SEED_STAMP's git_sha.
  # Nothing FUNCTIONAL read it (the Version tile reads motdeck.yaml `version:`), which is
  # exactly why the gap stayed invisible; a release marker that only exists in the repo is
  # not a release marker. Do not drop it again.
  [[ -f "$STAGE/VERSION" ]] \
    || { echo "ERROR (fat): VERSION did not make it into the seed — the bundle would not name its own release."; exit 1; }
  # This is a SECOND rsync entry point into the runtime seed. Keep the macOS metadata
  # exclusion here as well as on the main source copy; otherwise opening docs in Finder
  # can make a clean Git tree produce a dirty runtime archive.
  [[ -d docs ]]   && rsync -a --exclude='.git' --exclude='.DS_Store' docs "$STAGE/" 2>/dev/null || true
  [[ -f README.md ]] && cp README.md "$STAGE/" 2>/dev/null || true
  # the pinned llama-server binary + its dylibs
  mkdir -p "$STAGE/data/llamacpp/build"
  cp -R data/llamacpp/build/bin "$STAGE/data/llamacpp/build/"
  # BUILD STAMP — identifies WHICH bundle a snapshot was provisioned from.
  # firstrun_fat.sh compares it against an existing snapshot's .seed_stamp and refuses
  # to seed BACKWARDS (2026-08-20 incident: an early-August /Applications bundle rolled
  # a live 6-component install back to a 3-component, pre-voice manifest).
  SEED_GIT_SHA="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
  SEED_DIRTY_FILES="$(git -C "$ROOT" status --porcelain=v1 --untracked-files=normal \
    2>/dev/null | wc -l | tr -d ' ')"
  [[ "$SEED_DIRTY_FILES" =~ ^[0-9]+$ ]] || SEED_DIRTY_FILES=0
  if [[ "$SEED_DIRTY_FILES" -gt 0 && "$SEED_GIT_SHA" != "unknown" ]]; then
    SEED_GIT_SHA="${SEED_GIT_SHA}-dirty"
  fi
  {
    echo "date=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "git_sha=${SEED_GIT_SHA}"
    echo "dirty_files=${SEED_DIRTY_FILES}"
    echo "components=$(awk '/^components:/{f=1;next} f && /^[^ ]/{exit} f && /^  [A-Za-z0-9_-]+:/{n++} END{print n+0}' motdeck.yaml)"
  } > "$STAGE/SEED_STAMP"
  # Ownership is per file and digest. It lets a later, explicit upgrade retire an
  # obsolete seed-owned file without ever claiming a whole directory as disposable.
  "$PYBIN" "$ROOT/scripts/seed_ownership.py" write "$STAGE" "$STAGE/SEED_FILES.json" \
    || { echo "ERROR (fat): could not record seed file ownership"; exit 1; }
  [[ ! -d "$STAGE/bridge/tests" && ! -d "$STAGE/bridge/contract_tests" ]] \
    || { echo "ERROR (fat): runtime seed unexpectedly contains tests"; exit 1; }
  echo "[motdeck] seed stamp: $(tr '\n' ' ' < "$STAGE/SEED_STAMP")"
  # sanity: web_dist made it into the seed
  [[ -f "$STAGE/vendor/hermes/hermes_cli/web_dist/index.html" ]] \
    || { echo "ERROR (fat): Hermes web_dist not present in the staged seed."; exit 1; }
  # Keep the archive byte-for-byte inside the manifest's authority. macOS bsdtar can
  # synthesize AppleDouble `._*` members from xattrs unless COPYFILE_DISABLE is set;
  # those members are not files in STAGE and therefore are intentionally not owned.
  COPYFILE_DISABLE=1 tar czf "$RES/motdeck-seed-fat.tar.gz" -C "$STAGE" .
  rm -rf "$STAGE"
  echo "[motdeck] seed: $RES/motdeck-seed-fat.tar.gz ($(du -h "$RES/motdeck-seed-fat.tar.gz" | cut -f1))"

  # (6) the offline provisioner, run directly from the bundle by main.swift
  cp scripts/firstrun_fat.sh "$RES/firstrun_fat.sh"
  chmod +x "$RES/firstrun_fat.sh"

  # (7) ad-hoc codesign so the app opens on another Mac without the "damaged" error.
  # Full notarization needs an Apple Developer account (out of scope for personal use).
  echo "[motdeck] ad-hoc codesigning ${APP}…"
  codesign --force --deep --sign - "$APP" \
    && echo "[motdeck] ad-hoc signed (Debi's 2nd Mac may still need:  xattr -dr com.apple.quarantine <installed-app-path>)" \
    || echo "[motdeck] WARN (fat): ad-hoc codesign failed — the app may show 'damaged' on another Mac; fall back to  xattr -dr com.apple.quarantine <app>"

  echo "[motdeck] === FAT build complete — app payload $(du -sh "$APP" | cut -f1) ==="
fi

if [[ $DMG -eq 1 ]]; then
  echo "[motdeck] creating dmg..."
  rm -f "dist/MOT Deck.dmg"
  hdiutil create -volname "MOT Deck" -srcfolder "$APP" -ov -format UDZO "dist/MOT Deck.dmg" >/dev/null
  echo "[motdeck] built dist/MOT Deck.dmg"
fi

echo "[motdeck] done — open it with:  open \"$APP\""
