#!/usr/bin/env bash
# Build Harness.app (and optionally Harness.dmg with --dmg). Local build, no signing needed.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"

command -v swiftc >/dev/null || {
  echo "swiftc not found. Install Command Line Tools first:  xcode-select --install"; exit 1; }

APP=dist/Harness.app
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# bake the harness location into the binary so the app works from anywhere
cat > app/Config.swift <<EOF
// generated by build_app.sh — do not edit
let harnessRoot = "$ROOT"
EOF

echo "[harness] compiling Swift app..."
swiftc -O app/main.swift app/Config.swift -o "$APP/Contents/MacOS/Harness"

cat > "$APP/Contents/Info.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>Harness</string>
  <key>CFBundleIdentifier</key><string>local.harness.app</string>
  <key>CFBundleVersion</key><string>0.1</string>
  <key>CFBundleShortVersionString</key><string>0.1</string>
  <key>CFBundleExecutable</key><string>Harness</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSAppTransportSecurity</key>
  <dict><key>NSAllowsLocalNetworking</key><true/></dict>
</dict></plist>
EOF

# icon (optional): app/icon.png -> icns via sips/iconutil; skipped if missing
if [[ -f app/icon.png ]]; then
  echo "[harness] building icon..."
  ICONSET=dist/harness.iconset; rm -rf "$ICONSET"; mkdir -p "$ICONSET"
  for s in 16 32 64 128 256 512; do
    sips -z $s $s app/icon.png --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
    sips -z $((s*2)) $((s*2)) app/icon.png --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
  done
  iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/Harness.icns" \
    && /usr/libexec/PlistBuddy -c "Add :CFBundleIconFile string Harness" "$APP/Contents/Info.plist" \
    || echo "[harness] icon build failed (non-fatal)"
  rm -rf "$ICONSET"
fi

echo "[harness] built $APP"

if [[ "${1:-}" == "--dmg" ]]; then
  echo "[harness] creating dmg..."
  rm -f dist/Harness.dmg
  hdiutil create -volname Harness -srcfolder "$APP" -ov -format UDZO dist/Harness.dmg >/dev/null
  echo "[harness] built dist/Harness.dmg"
fi

echo "[harness] done — open it with:  open $APP"
