#!/usr/bin/env bash
# ship.sh — push current repo code into the FAT app snapshot and restart cleanly.
#
# Exists because the fat app serves a provisioned SNAPSHOT (~/Library/Application
# Support/Harness), not the repo, and the bridge is a separate process that can
# outlive the app (quit app ≠ restart bridge). Both traps have burned sessions.
# This script is THE way to ship: run it after any code change, done.
#
#   ./scripts/ship.sh          ship + restart
#
# What it does, in order:
#   1. repo bridge/panel + bridge/app.py + scripts/ + guards/ + policies/ → snapshot
#      (NEVER harness.yaml or data/ — those hold live state)
#   2. if app/main.swift is newer than the installed app binary → recompile the
#      Swift shell in place + ad-hoc re-sign (no full fat rebuild)
#   3. quit the app, kill the :8700 bridge LISTENER (components stay up),
#      relaunch, wait for the bridge, print a sanity check
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DST="$HOME/Library/Application Support/Harness"
APP="/Applications/Harness.app"

[[ -d "$DST" ]] || { echo "[ship] ERROR: no snapshot at $DST (fat app not provisioned?)"; exit 1; }
[[ -d "$APP" ]] || { echo "[ship] ERROR: $APP not found"; exit 1; }

echo "[ship] repo → snapshot (panel, bridge, scripts, guards, policies)"
cp -R "$ROOT/bridge/panel/." "$DST/bridge/panel/"
cp "$ROOT/bridge/app.py" "$DST/bridge/app.py"
for d in scripts guards policies; do
  [[ -d "$ROOT/$d" ]] && mkdir -p "$DST/$d" && cp -R "$ROOT/$d/." "$DST/$d/"
done

# Swift shell: recompile only when main.swift is newer than the installed binary.
if [[ "$ROOT/app/main.swift" -nt "$APP/Contents/MacOS/Harness" ]]; then
  echo "[ship] main.swift changed → recompiling the shell"
  if [[ ! -f "$ROOT/app/Config.swift" ]]; then
    cat > "$ROOT/app/Config.swift" <<EOF
// generated by ship.sh — do not edit
let harnessRoot = "$ROOT"
let fatBuild = true
EOF
  fi
  swiftc -O "$ROOT/app/main.swift" "$ROOT/app/Config.swift" -o "$APP/Contents/MacOS/Harness"
  codesign --force --sign - "$APP"
fi

echo "[ship] restarting app + bridge (components stay up)"
pkill -x Harness 2>/dev/null || true
sleep 2
lsof -ti tcp:8700 -sTCP:LISTEN 2>/dev/null | xargs kill -9 2>/dev/null || true
sleep 1
open "$APP"

printf "[ship] waiting for the bridge"
for _ in $(seq 1 30); do
  if curl -sf http://127.0.0.1:8700/status >/dev/null 2>&1 || \
     curl -sf http://127.0.0.1:8700/ >/dev/null 2>&1; then
    break
  fi
  printf "."; sleep 1
done
echo

MARK="$(curl -s http://127.0.0.1:8700/openapi.json | python3 -c 'import sys,hashlib; print(hashlib.sha1(sys.stdin.buffer.read()).hexdigest()[:8])' 2>/dev/null || echo none)"
SNAP="$(python3 -c 'import hashlib; print(hashlib.sha1(open("'"$DST"'/bridge/app.py","rb").read()).hexdigest()[:8])' 2>/dev/null || echo none)"
echo "[ship] bridge is up (api fingerprint $MARK, snapshot app.py $SNAP)"
echo "[ship] done — the served code now matches the repo. ⌘R open tabs if the panel looks stale."
