#!/usr/bin/env bash
# ship.sh — push current repo code into the FAT app snapshot and restart cleanly.
#
# Exists because the fat app serves a provisioned SNAPSHOT (~/Library/Application
# Support/MOT Deck), not the repo, and the bridge is a separate process that can
# outlive the app (quit app ≠ restart bridge). Both traps have burned sessions.
# This script is THE way to ship: run it after any code change, done.
#
#   ./scripts/ship.sh                       ship + restart
#   ./scripts/ship.sh --restart hermes      ... and restart that COMPONENT afterwards
#   ./scripts/ship.sh --restart a,b         ... comma list, or repeat the flag
#   SHIP_SKIP_GATE=1 ./scripts/ship.sh      ship WITHOUT the contract gate (loud)
#
# What it does, in order:
#   0. run the contract gate (scripts/verify.sh) and REFUSE to ship when it fails or
#      cannot run — a vendored pin bump once shipped with the gate silently skipped
#   1. repo bridge/panel + bridge/*.py + bridge/{core,routers}/*.py + scripts/
#      + guards/ + policies/ → snapshot
#      (NEVER motdeck.yaml or data/ — those hold live state)
#   2. if app/main.swift is newer than the installed app binary → recompile the
#      Swift shell in place + ad-hoc re-sign (no full fat rebuild)
#   3. quit the app, stop the OLD bridge (data/bridge.pid first, identity always),
#      start the NEW bridge in its OWN SESSION, wait for it, then relaunch the app
#      and print a sanity check.
#      "COMPONENTS STAY UP" IS NOW TRUE, AND WAS NOT BEFORE (2026-08-30 incident):
#      every component is spawned setsid'd by scripts/start_component.sh, so no
#      teardown of the app, the bridge or this script can reach them by process
#      group. Before the fix this line was a promise the script could not keep.
#   4. optionally restart named COMPONENTS from the snapshot (--restart)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DST="$HOME/Library/Application Support/MOT Deck"
APP=""
. "$ROOT/scripts/app_bundle_identity.sh"

# A user may rename the .app while preserving its internal identity. Resolve every
# immediate .app in the two installation
# roots by that identity, never by display name or an allowlist of filenames.
RESOLVE_FIXTURES=0
RESOLVE_FIXTURE_CANDIDATES=()
RESOLVE_FIXTURE_ROOTS=()
CONFIG_FIXTURES=0
CONFIG_FIXTURE_ROOT=""
CONFIG_FIXTURE_PATH=""
CONFIG_FIXTURE_MAIN=""
CONFIG_FIXTURE_BINARY=""
config_changed=0

_swift_string() {   # one Swift string literal payload, with no quoting ambiguity
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

_applescript_string() { # one AppleScript string literal payload
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

_prepare_swift_config() {   # <Config.swift path> <motdeck root>
  local config_path="$1" motdeck_root="$2" tmp escaped
  escaped="$(_swift_string "$motdeck_root")"
  tmp="${config_path}.tmp.$$"
  {
    printf '%s\n' '// generated by ship.sh — do not edit'
    printf 'let motdeckRoot = "%s"\n' "$escaped"
    printf '%s\n' 'let fatBuild = true'
  } > "$tmp" || { rm -f "$tmp"; return 1; }
  if [[ -f "$config_path" ]] && cmp -s "$tmp" "$config_path"; then
    rm -f "$tmp"
    config_changed=0
  else
    mv -f "$tmp" "$config_path"
    config_changed=1
  fi
}

_resolve_installed_app() {
  MOT_DECK_APP_RESOLVE_PREFIX="[ship]"
  if [[ "$RESOLVE_FIXTURES" -eq 1 && ${#RESOLVE_FIXTURE_ROOTS[@]} -eq 0 ]]; then
    motdeck_resolve_installed_app --candidates "${RESOLVE_FIXTURE_CANDIDATES[@]:-}" || return
  elif [[ ${#RESOLVE_FIXTURE_ROOTS[@]} -gt 0 ]]; then
    motdeck_resolve_installed_app --roots "${RESOLVE_FIXTURE_ROOTS[@]}" || return
  else
    motdeck_resolve_installed_app || return
  fi
  APP="$MOT_DECK_RESOLVED_APP"
  echo "[ship] selected installed app: $APP"
}

# ── args ──────────────────────────────────────────────────────────────────────
# --restart <name> is the sanctioned answer to the standing rule "shipping is NOT
# restarting a component": ship.sh deliberately leaves components up, so after a
# VENDORED upgrade the old process keeps serving and every verification against it
# is invalid (Hermes 0.20.1 shipped, 0.19.1 tested — a whole session lost).
RESTART=()
_add_restart() {   # accepts "a" or "a,b,c"
  local _p _old_ifs="$IFS"
  IFS=','
  for _p in $1; do [[ -n "$_p" ]] && RESTART+=("$_p"); done
  IFS="$_old_ifs"
}
while [[ $# -gt 0 ]]; do
  case "$1" in
    --restart)
      shift
      [[ $# -gt 0 ]] || { echo "[ship] ERROR: --restart needs a component name"; exit 1; }
      _add_restart "$1"; shift ;;
    --restart=*) _add_restart "${1#--restart=}"; shift ;;
    # Test-only: invokes the real resolver against only these temporary candidates,
    # then exits before the snapshot or any lifecycle operation is touched.
    --resolve-app-fixtures)
      RESOLVE_FIXTURES=1
      shift
      while [[ $# -gt 0 ]]; do
        RESOLVE_FIXTURE_CANDIDATES+=("$1")
        shift
      done
      ;;
    # Test-only: exercises the production recursive discovery beneath temporary roots.
    --resolve-app-root-fixtures)
      RESOLVE_FIXTURES=1
      shift
      while [[ $# -gt 0 ]]; do
        RESOLVE_FIXTURE_ROOTS+=("$1")
        shift
      done
      ;;
    # Test-only: writes only a fixture Config.swift, reports the real compile decision,
    # then exits before resolver, snapshot, bundle, process, or port work.
    --prepare-config-fixture)
      shift
      [[ $# -ge 4 ]] || { echo "[ship] ERROR: --prepare-config-fixture needs ROOT CONFIG MAIN BINARY"; exit 1; }
      CONFIG_FIXTURES=1
      CONFIG_FIXTURE_ROOT="$1"
      CONFIG_FIXTURE_PATH="$2"
      CONFIG_FIXTURE_MAIN="$3"
      CONFIG_FIXTURE_BINARY="$4"
      shift 4
      ;;
    -h|--help) sed -n '2,23p' "$0"; exit 0 ;;
    *) echo "[ship] ERROR: unknown argument '$1' (see ./scripts/ship.sh --help)"; exit 1 ;;
  esac
done

if [[ "$CONFIG_FIXTURES" -eq 1 ]]; then
  _prepare_swift_config "$CONFIG_FIXTURE_PATH" "$CONFIG_FIXTURE_ROOT" \
    || { echo "[ship] ERROR: could not prepare fixture Config.swift"; exit 1; }
  if [[ "$CONFIG_FIXTURE_MAIN" -nt "$CONFIG_FIXTURE_BINARY" || "$CONFIG_FIXTURE_PATH" -nt "$CONFIG_FIXTURE_BINARY" || "$config_changed" -eq 1 ]]; then
    echo "[ship] config_changed=$config_changed would_recompile=1"
  else
    echo "[ship] config_changed=$config_changed would_recompile=0"
  fi
  exit 0
fi

if ! _resolve_installed_app; then
  exit 1
fi
if [[ "$RESOLVE_FIXTURES" -eq 1 ]]; then
  exit 0
fi

# The bridge must leave this script's process group. Continuing without the one
# available macOS setsid path knowingly recreates the component-death incident, so
# reject before touching the snapshot, app, or any running process.
command -v perl >/dev/null 2>&1 || {
  echo "[ship] ERROR: perl is unavailable; refusing to launch the bridge without its own session."
  exit 1
}

# Config.swift is generated from THIS checkout on every real ship. It is never evidence
# of a prior root: keeping an old generated file would let an archived checkout survive
# a rebuild even after all copied code came from the canonical tree. This remains below
# the resolver fixture exit so fixture-only resolver tests cannot touch it.
_prepare_swift_config "$ROOT/app/Config.swift" "$ROOT" \
  || { echo "[ship] ERROR: could not prepare app/Config.swift"; exit 1; }

[[ -d "$DST" ]] || { echo "[ship] ERROR: no snapshot at $DST (fat app not provisioned?)"; exit 1; }
# A copied venv can retain console shebangs and PEP 660 editable maps into its former
# checkout. Repair generated pointers before the gate uses any repo venv; this helper
# is stdlib-only so it deliberately uses a host python, never the venv it is checking.
VENV_REPAIR_PY="$(command -v python3 || true)"
[[ -n "$VENV_REPAIR_PY" ]] || { echo "[ship] ERROR: no host python3 for relocated-venv repair"; exit 1; }
OWNED_VENV_ARGS=(
  --owned-venv bridge-venv --owned-venv hermes-venv
  --owned-venv mlx-venv --owned-venv odysseus-venv --owned-venv searxng-venv
  --owned-venv aider-venv --owned-venv comfyui-venv --owned-venv music-venv
  --owned-venv unsloth-venv --owned-venv voicebox-venv --owned-venv voicestudio-venv
)
_repair_deepseek_root() { # <root> <helper path>
  local target="$1" helper="$2" prefix home node=""
  prefix="$target/data/deepseek/npm"
  home="$target/data/deepseek/home"
  # No installed DeepSeek dependency tree means there are no owned profile links to
  # repair. Once installed, a stale generated tree is a hard refusal, not a warning.
  [[ -f "$prefix/node_modules/@deepseek-ai/dsh/package.json" ]] || return 0
  for node in "$target/data/node/bin/node" "$(command -v node 2>/dev/null || true)"; do
    [[ -n "$node" && -x "$node" ]] && break
    node=""
  done
  [[ -n "$node" ]] || {
    echo "[ship] ERROR: DeepSeek is installed under $target but no existing node runtime can repair its generated profile links."
    return 1
  }
  "$VENV_REPAIR_PY" "$helper" --prefix "$prefix" --home "$home" --node "$node"
}
echo "[ship] repair generated venv pointers in repository"
"$VENV_REPAIR_PY" "$ROOT/scripts/repair_relocated_venvs.py" --root "$ROOT" "${OWNED_VENV_ARGS[@]}" \
  || { echo "[ship] ERROR: repository relocated-venv repair refused or failed"; exit 1; }
echo "[ship] repair generated DeepSeek profile links in repository"
_repair_deepseek_root "$ROOT" "$ROOT/scripts/repair_deepseek_profiles.py" \
  || { echo "[ship] ERROR: repository DeepSeek profile repair refused or failed"; exit 1; }
# ── contract gate (runs BEFORE anything is copied) ────────────────────────────
# The gate used to be a manual step, which means it was a step that could be — and
# was — skipped. Now the ONLY way past a red gate is to say so out loud.
if [[ "${SHIP_SKIP_GATE:-0}" == "1" ]]; then
  echo "[ship] WARNING: SHIP_SKIP_GATE=1 — THE CONTRACT GATE WAS SKIPPED."
  echo "[ship]          You are shipping code whose upstream contracts are unverified."
else
  echo "[ship] contract gate: scripts/verify.sh"
  GATE_RC=0
  bash "$ROOT/scripts/verify.sh" || GATE_RC=$?
  if [[ "$GATE_RC" -eq 1 ]]; then
    echo "[ship] REFUSING TO SHIP - the contract gate FAILED (output above)."
    echo "[ship]   NOTHING was copied and the app was not touched."
    echo "[ship]   Fix the failures, or ship anyway with:  SHIP_SKIP_GATE=1 ./scripts/ship.sh"
    exit 1
  elif [[ "$GATE_RC" -ne 0 ]]; then
    echo "[ship] REFUSING TO SHIP - the contract gate COULD NOT RUN (reason above)."
    echo "[ship]   NOTHING was copied and the app was not touched."
    echo "[ship]   Fix that, or ship anyway with:  SHIP_SKIP_GATE=1 ./scripts/ship.sh"
    exit 1
  fi
fi

echo "[ship] repo → snapshot (panel, bridge, scripts, guards, policies)"
cp -R "$ROOT/bridge/panel/." "$DST/bridge/panel/"
# EVERY top-level bridge module, not just app.py: app.py now imports sibling modules
# (bridge/voice.py, Phase B) and copying only app.py would ship an app.py whose import
# target does not exist in the snapshot. app.py degrades gracefully if voice.py is
# missing, but the snapshot must simply carry the whole package.
# ⚠️ PENDING FABLE QA — ship.sh is the critical ops path and the manifest-merge note
# in CLAUDE.md makes changes here Fable-lane. This one is minimal and additive (same
# destination dir, no new semantics, subdirectories untouched), and the alternative
# was a bridge that cannot import on the first ship. Flagged, not assumed.
for _m in "$ROOT"/bridge/*.py; do
  cp "$_m" "$DST/bridge/$(basename "$_m")"
done
# ⚠️ AND THE TWO PACKAGE DIRECTORIES, WHICH THE GLOB ABOVE DOES NOT REACH. app.py is a
# FACADE since the router/core split (2026-08-28): the routes and the logic live in
# bridge/core/*.py and bridge/routers/*.py, and app.py imports them. Shipping only the
# top-level *.py would put a 250-line facade into the snapshot with nothing behind it —
# the bridge would not import at all, which is the loudest possible version of this
# failure and still worth spelling out, because the glob LOOKED complete for a year.
# Everything else under bridge/ (tests/, contract_tests/, __pycache__/) stays out, as
# it always has: the snapshot runs the bridge, it does not test it.
#
# ⚠️ RECURSIVE, NOT A FLAT GLOB — AND FENCED (bug-echo W-02). `cp "$pkg"/*.py` ships ONE
# LEVEL. The comment above says why the packages must be copied at all, but the glob
# itself repeated the shape of the near-miss it exists to fix: the day either package
# grows a SUBpackage (`bridge/core/foo/*.py`), the snapshot silently loses it and the
# bridge fails to import IN THE APP while the repo runs perfectly. So: every `*.py` at
# every depth, with its directory structure. __pycache__ still never travels.
_pkg_pys() {   # every .py under bridge/$1, relative to it, __pycache__ pruned
  ( cd "$ROOT/bridge/$1" 2>/dev/null \
    && find . -name '__pycache__' -prune -o -name '*.py' -print ) | sed 's|^\./||'
}
for _pkg in core routers; do
  [[ -d "$ROOT/bridge/$_pkg" ]] || continue
  mkdir -p "$DST/bridge/$_pkg"
  while IFS= read -r _f; do
    [[ -n "$_f" ]] || continue
    mkdir -p "$DST/bridge/$_pkg/$(dirname "$_f")"
    cp "$ROOT/bridge/$_pkg/$_f" "$DST/bridge/$_pkg/$_f"
  done < <(_pkg_pys "$_pkg")
done
# AND THE FENCE, because "recursive today" is not "recursive for ever": a future edit
# that reverts to a glob, or a single copy that fails, must STOP THE SHIP rather than
# leave a snapshot that cannot import. Every .py the repo's packages hold must be in the
# snapshot, by path. This is the assertion the flat glob never had.
_missing=""
for _pkg in core routers; do
  [[ -d "$ROOT/bridge/$_pkg" ]] || continue
  while IFS= read -r _f; do
    [[ -n "$_f" ]] || continue
    [[ -f "$DST/bridge/$_pkg/$_f" ]] || _missing="$_missing bridge/$_pkg/$_f"
  done < <(_pkg_pys "$_pkg")
done
if [[ -n "$_missing" ]]; then
  echo "[ship] ERROR: these package modules did not reach the snapshot:$_missing"
  echo "[ship]   The snapshot is INCOMPLETE — the bridge in the app would fail to"
  echo "[ship]   import. Nothing was restarted. Fix the copy above and ship again."
  exit 1
fi
for d in scripts guards policies; do
  [[ -d "$ROOT/$d" ]] && mkdir -p "$DST/$d" && cp -R "$ROOT/$d/." "$DST/$d/"
done

# Older FAT seeds copied the authoring tests into the runtime root even though no
# runtime path imports or executes them. Retire only exact bytes recorded from known
# historical seeds. Modified/unknown files are preserved and named by the helper.
# This is intentionally after the new helper reaches the snapshot and before restart.
_LEGACY_TEST_MANIFEST="$ROOT/scripts/seed_manifests/legacy-runtime-tests.json"
if [[ -f "$_LEGACY_TEST_MANIFEST" ]]; then
  "$VENV_REPAIR_PY" "$DST/scripts/seed_ownership.py" clean-known-tests \
    "$DST" "$_LEGACY_TEST_MANIFEST" \
    || { echo "[ship] ERROR: legacy seed cleanup refused or failed"; exit 1; }
fi

# Config.swift is generated source, but a fat snapshot carries a copy beside its app
# sources.  Recompiling the installed binary from the canonical repo is not enough:
# leaving that copy behind made a forensic root-severance scan truthfully report the
# archived Claude checkout even while the binary itself used this checkout.  Mirror
# only this generated file (never the app directory wholesale), refuse symlink-shaped
# destinations, replace atomically, and fence the bytes.  It is not live state.
[[ ! -L "$DST/app" ]] || {
  echo "[ship] ERROR: snapshot app directory is a symlink; refusing Config.swift sync"
  exit 1
}
mkdir -p "$DST/app"
[[ ! -e "$DST/app/Config.swift" || ( -f "$DST/app/Config.swift" && ! -L "$DST/app/Config.swift" ) ]] || {
  echo "[ship] ERROR: snapshot app/Config.swift is not a regular no-follow file"
  exit 1
}
if ! cmp -s "$ROOT/app/Config.swift" "$DST/app/Config.swift"; then
  _swift_tmp="$(mktemp "$DST/app/.Config.swift.ship.XXXXXX")" || exit 1
  cp "$ROOT/app/Config.swift" "$_swift_tmp" || { rm -f "$_swift_tmp"; exit 1; }
  mv -f "$_swift_tmp" "$DST/app/Config.swift" || { rm -f "$_swift_tmp"; exit 1; }
fi
cmp -s "$ROOT/app/Config.swift" "$DST/app/Config.swift" || {
  echo "[ship] ERROR: generated Config.swift did not reach the snapshot"
  exit 1
}

# The snapshot retains its own generated venvs while code is copied around them. Run
# the same narrow repair after the helper itself has reached the snapshot and before a
# bridge/component can be restarted; a healthy snapshot is simply an idempotent no-op.
echo "[ship] repair generated venv pointers in snapshot"
"$VENV_REPAIR_PY" "$DST/scripts/repair_relocated_venvs.py" --root "$DST" "${OWNED_VENV_ARGS[@]}" \
  || { echo "[ship] ERROR: snapshot relocated-venv repair refused or failed"; exit 1; }
echo "[ship] repair generated DeepSeek profile links in snapshot"
_repair_deepseek_root "$DST" "$DST/scripts/repair_deepseek_profiles.py" \
  || { echo "[ship] ERROR: snapshot DeepSeek profile repair refused or failed"; exit 1; }

# ── VERSION: the release number the app now READS (U56, 2026-09-02) ───────────
# Until this line the top-level VERSION file was copied by exactly one thing — the FAT
# SEED in build_app.sh — which runs on a full rebuild and not on a slice. So the moment
# the bridge started reading ROOT/VERSION (bridge/core/procs.py::motdeck_version), the
# snapshot's copy would have frozen at whatever release last rebuilt the DMG and the
# tile would have gone on lying with a different number. ship.sh is THE way code reaches
# the app, so the number that names that code ships with it.
# Absence is honest, not fatal: the bridge reads a missing VERSION as "unknown" with a
# sentence, so a copy that cannot happen must not stop a ship.
if [[ -f "$ROOT/VERSION" ]]; then
  cp "$ROOT/VERSION" "$DST/VERSION" \
    || echo "[ship] WARN: could not copy VERSION — the app's Version tile will read stale"
fi

# ── the TOP-LEVEL docs/*.md, and only those ───────────────────────────────────
# ⚠️ PENDING FABLE QA — ops-path edit, flagged rather than assumed, per the note above.
#
# WHY IT IS HERE AT ALL. The panel's Help view (roadmap §2.4) renders
# docs/USER-EXPLAINERS.md through /api/help/explainers, which reads it off ROOT — and
# ROOT in the fat app is the SNAPSHOT. Nothing copied docs/ before this line, so Help
# would have been permanently empty in the only place it matters while working
# perfectly in the repo. That is the exact shape of the bridge/{core,routers} near-miss
# above, so it gets the same treatment: an explicit copy with the reason next to it.
#
# WHY `*.md` AT THE TOP LEVEL AND NOT `cp -R docs/`. docs/handoff (972K) and
# docs/research (596K) are session archaeology and internal briefs — they are not
# shipped product, and a recursive copy would put them in the user's Application
# Support folder for no reason. Seven files, ~136K, is what the app can actually use.
# A `docs/` subdirectory that becomes shippable later must be added deliberately.
#
# NOT FENCED like the package copy, and that is a judgement, not an omission: a missing
# bridge/core/*.py means the bridge cannot import, which must stop the ship; a missing
# explainer means the Help view shows its named empty state ("run ./scripts/ship.sh"),
# which is a degradation the user can read and act on. It must not block a ship.
if [[ -d "$ROOT/docs" ]]; then
  mkdir -p "$DST/docs"
  for _d in "$ROOT"/docs/*.md; do
    [[ -f "$_d" ]] && cp "$_d" "$DST/docs/$(basename "$_d")"
  done
fi

# A FAT snapshot also retains a very small repo-owned authoring surface.  Mirror only
# the explicit allowlist in this helper and retire only the three exact pre-U150 names
# after their replacements are byte-verified.  Never mirror these directories: app/
# contains generated assets, skills/ may contain learned user material, and docs/
# contains intentionally retained forensic history.  Live state and data/ are outside
# the helper's authority entirely.
"$VENV_REPAIR_PY" "$ROOT/scripts/sync_snapshot_identity.py" "$ROOT" "$DST" \
  || { echo "[ship] ERROR: snapshot repo-owned identity sync failed"; exit 1; }

# Swift shell: recompile when its source OR the generated root/build-kind changed.
# ⚠️ PENDING FABLE QA — ops-path edit (this block and the app-mark block below,
# 2026-09-02). _RESIGN replaces the codesign call that used to sit INSIDE the swiftc
# branch: the bundle's ad-hoc signature covers Contents/Resources as well as the binary,
# so REPLACING THE .icns invalidates it exactly as replacing the binary does. One
# re-sign after both branches is the only version of this that cannot go stale.
_RESIGN=0
if [[ "$ROOT/app/main.swift" -nt "$APP/Contents/MacOS/MOTDeck" || "$ROOT/app/Config.swift" -nt "$APP/Contents/MacOS/MOTDeck" || "$config_changed" -eq 1 ]]; then
  if [[ "$config_changed" -eq 1 ]]; then
    echo "[ship] generated Config.swift changed → recompiling the shell"
  else
    echo "[ship] main.swift changed → recompiling the shell"
  fi
  swiftc -O "$ROOT/app/main.swift" "$ROOT/app/Config.swift" -o "$APP/Contents/MacOS/MOTDeck"
  _RESIGN=1
fi

# ── THE APP MARK ("M.O.T", 2026-09-02) ────────────────────────────────────────
# WHY SHIP.SH CARRIES THE ICON AND scripts/build_app.sh IS NOT ENOUGH. build_app.sh
# builds the icon from app/icon.png with ten `sips -z` downscales, and it only runs on a
# FULL fat rebuild — which is not what a normal slice does. ship.sh is THE way code
# reaches the app, so a mark that only build_app.sh installs is a mark that reverts to
# whatever the last fat build produced and then never updates again. And the downscale
# path cannot produce this mark anyway: "M.O.T" box-filtered to 16px is five smudges and
# the two periods are the first pixels a downscaler discards. So app/MOTDeck.icns is
# drawn PER SIZE by app/make_icon.swift (the wordmark at ≥64px, a matching "M" at ≤32px)
# and committed — copying that committed file is both the fix and the reason there is a
# file to copy.
# _MARK_CHANGED covers BOTH halves of the app's identity — the icon below and the
# display name after it — because both need the same Launch Services / Dock refresh at
# the end, and a ship that changed only one of them still has to do it.
_MARK_CHANGED=0
if [[ -f "$ROOT/app/MOTDeck.icns" ]]; then
  if ! cmp -s "$ROOT/app/MOTDeck.icns" "$APP/Contents/Resources/MOTDeck.icns"; then
    echo "[ship] app mark changed → installing app/MOTDeck.icns"
    cp "$ROOT/app/MOTDeck.icns" "$APP/Contents/Resources/MOTDeck.icns"
    # CFBundleIconFile: Set if the key is there, Add if it is not. Both best-effort — a
    # bundle whose Info.plist we cannot edit still gets the new .icns, and the key has
    # been present since build_app.sh first wrote it.
    /usr/libexec/PlistBuddy -c "Set :CFBundleIconFile MOTDeck" "$APP/Contents/Info.plist" >/dev/null 2>&1 \
      || /usr/libexec/PlistBuddy -c "Add :CFBundleIconFile string MOTDeck" "$APP/Contents/Info.plist" >/dev/null 2>&1 \
      || echo "[ship] WARN: could not set CFBundleIconFile — the new .icns is installed but may not be read"
    _MARK_CHANGED=1
    _RESIGN=1
  fi
fi

# ── ONE PUBLIC NAME: MOT Deck (U150, Debi 2026-09-07) ─────────────────────────
#
# WHERE THE NAME COMES FROM. The Dock's hover label is Launch Services' display name
# for the bundle (`lsappinfo info -only name <asn>` prints exactly it). LS resolves it
# as: a LOCALIZED name from Contents/Resources/<lang>.lproj/InfoPlist.strings, else
# CFBundleDisplayName, else the .app FILENAME. The installed bundle had neither key —
# its CFBundleName still carried the retired product identity — so the filename won by
# default and Finder/Dock exposed that retired name.
#
# The installed filename is still not lifecycle authority: ship.sh resolves the exact
# `local.motdeck.app` + `MOTDeck` bundle before it touches anything.
#
# WHY IT IS HERE AND NOT ONLY IN build_app.sh: same reason as the icon above — ship.sh
# is THE way code reaches the app, and build_app.sh only runs on a full fat rebuild.
# Idempotent: the block is a no-op once the keys already say MOT Deck.
_APP_NAME="MOT Deck"
_plist_put() {   # <key> <value> — Set if present, Add if not; loud only if both fail
  /usr/libexec/PlistBuddy -c "Set :$1 $2" "$APP/Contents/Info.plist" >/dev/null 2>&1 \
    || /usr/libexec/PlistBuddy -c "Add :$1 string $2" "$APP/Contents/Info.plist" >/dev/null 2>&1 \
    || echo "[ship] WARN: could not set $1"
}
_HAVE_NAME="$(/usr/libexec/PlistBuddy -c "Print :CFBundleDisplayName" \
                "$APP/Contents/Info.plist" 2>/dev/null || true)"
if [[ "$_HAVE_NAME" != "$_APP_NAME" ]]; then
  echo "[ship] app name → $_APP_NAME (Dock hover + the menu bar)"
  # CFBundleDisplayName is what the Dock/Finder read; CFBundleName is what the MENU BAR
  # reads (and it must agree, or the app menu says one thing while hover says another —
  # the incoherence this slice exists to end). The mic prompt names the app to the user
  # in a system dialog, so it moves with them.
  _plist_put CFBundleDisplayName "$_APP_NAME"
  _plist_put CFBundleName "$_APP_NAME"
  _plist_put NSMicrophoneUsageDescription \
             "'$_APP_NAME uses the microphone for voice dictation into chat.'"
  # ⚠️ AND A LOCALIZED NAME, BECAUSE CFBundleDisplayName ALONE IS NOT RELIABLY HONOURED:
  # Apple's own rule is that a display name which does NOT match the filename may be
  # ignored (it is an anti-spoofing measure), while a LOCALIZED name always wins. en is
  # the only localization this bundle has ever claimed, so en.lproj is the whole job.
  mkdir -p "$APP/Contents/Resources/en.lproj"
  printf 'CFBundleDisplayName = "%s";\nCFBundleName = "%s";\n' \
         "$_APP_NAME" "$_APP_NAME" > "$APP/Contents/Resources/en.lproj/InfoPlist.strings"
  _MARK_CHANGED=1
  _RESIGN=1
fi

# Finder/Get Info reads the bundle version, while the panel reads ROOT/VERSION. Both
# must name the same release. This is synchronization at a packaging boundary, not a
# second source: VERSION is read here and the postcondition is verified immediately.
_RELEASE_VERSION="$(tr -d '\r\n' < "$ROOT/VERSION")"
[[ "$_RELEASE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || {
  echo "[ship] ERROR: VERSION is not a dotted release number: $_RELEASE_VERSION"; exit 1; }
_HAVE_BUNDLE_VERSION="$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" \
                         "$APP/Contents/Info.plist" 2>/dev/null || true)"
if [[ "$_HAVE_BUNDLE_VERSION" != "$_RELEASE_VERSION" ]]; then
  echo "[ship] app bundle version → $_RELEASE_VERSION"
  _plist_put CFBundleVersion "$_RELEASE_VERSION"
  _plist_put CFBundleShortVersionString "$_RELEASE_VERSION"
  _AFTER_BUNDLE_VERSION="$(/usr/libexec/PlistBuddy -c \
      "Print :CFBundleShortVersionString" "$APP/Contents/Info.plist" 2>/dev/null || true)"
  [[ "$_AFTER_BUNDLE_VERSION" == "$_RELEASE_VERSION" ]] || {
    echo "[ship] ERROR: installed app bundle version did not update"; exit 1; }
  _MARK_CHANGED=1
  _RESIGN=1
fi

if [[ "$_RESIGN" -eq 1 ]]; then
  codesign --force --sign - "$APP"
fi

if [[ "$_MARK_CHANGED" -eq 1 ]]; then
  # ⚠️ THE ICON *AND NAME* CACHE, AND WHY IT IS NOT A `killall`. macOS caches a bundle's
  # icon and its display name, and will keep showing the OLD tile and the OLD hover label
  # for an unbounded time after either changes — so a new mark or name that nobody can
  # see is the default outcome. Three supported steps, in order:
  #   1. `touch` the bundle — invalidates the cache entry keyed on its mtime;
  #   2. lsregister -f — asks Launch Services to re-read this ONE bundle (not the whole
  #      machine: `lsregister -kill -r` rebuilds every app's registration and can take
  #      minutes; a ship has no business doing that);
  #   3. launchctl kickstart -k on com.apple.Dock.agent — launchd's OWN restart of the
  #      Dock, addressed by SERVICE NAME in the user's GUI domain.
  #
  # ⛔ Debi authorised "killall Dock" for this (2026-09-02: "Dock restart is allowed,
  # it's the system Dock refresh idiom"). It is deliberately NOT what this does. The
  # PROCESS-KILL RULE's contract test (bridge/contract_tests/test_no_name_kills_contract.py)
  # bans `killall` from every shell file here with no exception list, and the right answer
  # to a banned-by-name pattern is not an exception — it is the supported call that does
  # not need one. `launchctl kickstart` asks launchd to restart a service it owns; it
  # never enumerates processes, never matches a name against `ps`, and cannot hit a
  # standalone app of Debi's the way `killall` can. Same effect, inside the rule.
  #
  # All three are fenced to fire ONLY when the mark actually changed, so a routine ship
  # touches none of them.
  echo "[ship] refreshing the icon/name cache (touch + lsregister -f + Dock kickstart)"
  touch "$APP"
  _LSREG="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
  [[ -x "$_LSREG" ]] && "$_LSREG" -f "$APP" >/dev/null 2>&1 || true
  launchctl kickstart -k "gui/$(id -u)/com.apple.Dock.agent" >/dev/null 2>&1 \
    || echo "[ship] note: the Dock did not reload — log out/in, or run: launchctl kickstart -k gui/\$(id -u)/com.apple.Dock.agent"
fi

# motdeck.yaml is NEVER copied wholesale (the snapshot's copy holds LIVE state:
# installed flags, runner.model, aux.model). But a NEW component or build pin added
# in the repo would then never reach the app — its card simply never appears. So:
# ADDITIVE merge by default. Existing keys/values in the snapshot are never touched;
# new components arrive as installed:false (install state is per-machine). Named
# release-pin migrations are exact grouped compare-and-swaps: a tag and its digest
# advance together only from the exact previously shipped values. Mixed groups fail;
# operator-custom values are preserved. Any other live pin is untouched.
# One stdlib transaction now owns every motdeck.yaml write: flock, latest read,
# line-preserving additive transform, same-directory fsync+replace. It never serializes
# live state through PyYAML, so empty values cannot become literal `null` and comments,
# ordering, pins, install flags and unrelated bytes remain exact.
"$DST/data/bridge-venv/bin/python" "$ROOT/scripts/merge_manifest.py" \
  "$ROOT/motdeck.yaml" "$DST/motdeck.yaml"

echo "[ship] restarting app + bridge (components stay up)"
# ⛔ PROCESS-KILL RULE (CLAUDE.md; U19 echo sweep 2026-08-29). This used to be
#   a broad pkill by the old executable name → a kill BY NAME
#   lsof -ti tcp:8700 | xargs kill -9  → a port clear with NO ownership check at all
# Both are the class that closed Debi's standalone Unsloth and goose Desktop. Now:
#   1. ask OUR app to quit (an Apple Event to the app, not a signal by name);
#   2. a survivor is reported and the ship FAILS — an executable path corroborates
#      identity but cannot prove that this invocation launched the process;
#   3. the :8700 listener is reaped only with the exact launch record written by its
#      spawner — a stranger on :8700 stops the ship with the honest reason instead.
_ship_app_pids() {   # pids whose executable path IS "$APP" (path evidence, not a name)
  ps -Ao pid=,command= 2>/dev/null | awk -v p="$APP/Contents/MacOS/" \
    '{ pid=$1; $1=""; sub(/^[[:space:]]+/,""); if (index($0, p) == 1) print pid }'
}
_APP_AS="$(_applescript_string "$APP")"
osascript -e "tell application \"$_APP_AS\" to quit" >/dev/null 2>&1 || true
for _ in $(seq 1 10); do
  [[ -z "$(_ship_app_pids)" ]] && break
  sleep 1
done
for _pid in $(_ship_app_pids); do
  echo "[ship] REFUSING to ship: the selected app's pid $_pid did not quit after the targeted Apple Event."
  echo "[ship]   Its bundle path matches, but path evidence alone is not launch ownership."
  echo "[ship]   Quit that MOT Deck window explicitly, then re-run ./scripts/ship.sh."
  exit 1
done
sleep 1
# ── REAPING THE OLD BRIDGE: LAUNCH RECORD OR NO SIGNAL ──────────────────────
# The spawner records the exact child PID plus its kernel birth stamp. Paths, names,
# CWD, a listener, and a plain pidfile remain diagnostics and never become authority.
# Verification + signal + cleanup use the same locked primitive as component stops;
# splitting them into shell syscalls would leave a relaunch race.
_ownership_cli() {
  "$DST/data/bridge-venv/bin/python" "$DST/bridge/core/ownership.py" "$@"
}
_bridge_owner_ok() { _ownership_cli matches "$DST" bridge "$1" >/dev/null 2>&1; }
_bridge_stop() {   # <pid> <why>
  local pid="$1" why="$2" detail birth
  birth="$(awk -F '\t' -v p="$pid" '$1 == "v1" && $2 == p {print $3; exit}' \
    "$DST/data/bridge.owner" 2>/dev/null || true)"
  if ! detail="$(_ownership_cli signal "$DST" bridge "$pid" --birth "$birth" --keep-claim 2>&1)"; then
    return 1
  fi
  echo "[ship] stopping the previous bridge, pid $pid ($why, launch record verified)"
  for _ in $(seq 1 12); do
    if ! kill -0 "$pid" 2>/dev/null; then
      # The graceful shutdown normally releases its own claim. If hard process exit
      # skipped that hook, the locked helper recognizes and discards only this stale
      # claim; a concurrent new bridge claim cannot be erased.
      _ownership_cli retire "$DST" bridge "$pid" --birth "$birth" >/dev/null 2>&1 || true
      return 0
    fi
    sleep 1
  done
  echo "[ship] bridge pid $pid ignored SIGTERM for 12s — SIGKILL (same launch record reverified)"
  _ownership_cli signal "$DST" bridge "$pid" --birth "$birth" --force >/dev/null 2>&1
}
_BPF="$DST/data/bridge.pid"
if [[ -f "$_BPF" ]]; then
  _bpid="$(tr -cd '0-9' < "$_BPF" 2>/dev/null || true)"
  if [[ -n "$_bpid" ]] && kill -0 "$_bpid" 2>/dev/null; then
    _bridge_stop "$_bpid" "data/bridge.pid" \
      || echo "[ship] data/bridge.pid names pid $_bpid without a matching launch record — leaving it alone."
  fi
fi
for _pid in $(lsof -ti tcp:8700 -sTCP:LISTEN 2>/dev/null); do
  _cmd="$(ps -o command= -p "$_pid" 2>/dev/null | tr '\n' ' ')"
  [[ -z "$_cmd" ]] && continue            # vanished between the probe and the check
  if ! _bridge_stop "$_pid" "the :8700 listener plus exact launch record"; then
    echo "[ship] REFUSING to ship: :8700 is held by pid $_pid without a matching MOT Deck launch record:"
    echo "[ship]   $_cmd"
    echo "[ship]   Stop that process yourself, then re-run ./scripts/ship.sh."
    exit 1
  fi
done
sleep 1

# ── SHIP LAUNCHES THE BRIDGE, DETACHED, BEFORE THE APP ────────────────────────
# Two reasons, both from the 2026-08-30 incident:
#   · OWN SESSION. A bridge in ship.sh's process group would be reaped along with
#     this script by anything that tears down the agent/terminal process tree —
#     the same class of bug that killed the components. setsid via perl, exactly as
#     scripts/start_component.sh's _detached does it (macOS has no setsid binary).
#   · IT SETTLES THE RACE. app/main.swift only spawns a bridge when :8700 is NOT
#     already answering. By starting one here and WAITING for it before `open`, the
#     app always finds a live bridge, never spawns its own, and its
#     applicationWillTerminate therefore has nothing of ours to terminate — so
#     "components stay up" in this script's header is now true of the bridge too.
#     If this launch somehow fails, the app still spawns its own bridge on the old
#     path and the singleton guard keeps exactly one of them alive: the app always
#     ends up with a working :8700 either way.
echo "[ship] starting the snapshot bridge (own session, detached from this script)"
SHIP_NONCE="$("$DST/data/bridge-venv/bin/python" -c 'import secrets; print(secrets.token_hex(32))')"
(
  cd "$DST"
  MOT_DECK_LAUNCH_NONCE="$SHIP_NONCE" nohup perl -MPOSIX -e '
    my $s = POSIX::setsid();
    if (!defined($s) || $s < 0) {
      die "[ship] detach: setsid failed ($!) - refusing unsafe bridge launch\n";
    }
    exec { $ARGV[0] } @ARGV or die "[ship] detach: cannot exec $ARGV[0]: $!\n";
  ' -- "$DST/data/bridge-venv/bin/python" -m uvicorn bridge.app:app \
        --host 127.0.0.1 --port 8700 --timeout-graceful-shutdown 10 \
    >>"$DST/data/logs/bridge.log" 2>&1 &
  _bridge_child="$!"
  # perl execs the bridge without changing PID; this is the exact child handle owned
  # by this launch site, recorded before the bridge finishes its guarded import.
  bash "$DST/scripts/start_component.sh" --record-child bridge "$_bridge_child"
)
SHIP_CLAIM="$(_ownership_cli claim "$DST" bridge)" || {
  echo "[ship] REFUSING to open: the bridge launch did not publish an ownership claim."
  exit 1
}
SHIP_BRIDGE_PID="${SHIP_CLAIM%%$'\t'*}"
# 90s, not 30: a cold snapshot bridge (imports + registry read) can legitimately
# take longer than 30s.  GET /api/status is the control API's health truth; a static
# page response only proves that something can serve HTML and must never turn green.
# Do not open the app after this fails: that would restart it against a bridge this
# ship has already proved unhealthy.
SHIP_WAIT_S=90
UP=0
printf "[ship] waiting for the bridge"
for _ in $(seq 1 "$SHIP_WAIT_S"); do
  if curl -sf -m 2 http://127.0.0.1:8700/api/status >/dev/null 2>&1; then
    UP=1; break
  fi
  printf "."; sleep 1
done
echo

if [[ "$UP" -ne 1 ]]; then
  echo "[ship] BRIDGE CONTROL API DID NOT ANSWER GET /api/status within ${SHIP_WAIT_S}s."
  echo "[ship] The app was not opened; fix the snapshot bridge, then ship again."
  if [[ -f "$DST/data/logs/bridge.log" ]]; then
    tail -15 "$DST/data/logs/bridge.log" || true
  else
    echo "[ship] (no $DST/data/logs/bridge.log yet)"
  fi
  exit 1
fi

# A 2xx alone is not proof that OUR newly launched bridge answered. Bind the response
# to the exact recorded child and validate the control-API shape before opening MOT Deck.
_served_pid="$(lsof -ti tcp:8700 -sTCP:LISTEN 2>/dev/null | head -1)"
if [[ -z "$_served_pid" || "$_served_pid" != "$SHIP_BRIDGE_PID" ]] \
   || ! _bridge_owner_ok "$_served_pid"; then
  echo "[ship] REFUSING to open: /api/status answered, but :8700 is not the exact bridge child this ship launched."
  exit 1
fi
STATUS_JSON="$(curl -sf -m 3 http://127.0.0.1:8700/api/status)"
_served_after="$(lsof -ti tcp:8700 -sTCP:LISTEN 2>/dev/null | head -1)"
if [[ "$_served_after" != "$SHIP_BRIDGE_PID" ]] \
   || ! _ownership_cli matches "$DST" bridge "$SHIP_BRIDGE_PID" >/dev/null 2>&1; then
  echo "[ship] REFUSING to open: :8700 changed owner while /api/status was read."
  exit 1
fi
if ! printf '%s' "$STATUS_JSON" | "$DST/data/bridge-venv/bin/python" -c '
import json, sys
expected_nonce = sys.argv[1]
value = json.load(sys.stdin)
ok = (isinstance(value, dict) and value.get("bridge") == "ok"
      and value.get("bridge_schema") == 1
      and value.get("launch_nonce") == expected_nonce
      and isinstance(value.get("components"), dict))
raise SystemExit(0 if ok else 1)
' "$SHIP_NONCE"; then
  echo "[ship] REFUSING to open: /api/status did not return the MOT Deck control-API contract."
  exit 1
fi

open "$APP"

# An EMPTY curl body still hashes — to da39a3ee (sha1 of nothing). Printing that as
# a "fingerprint" alongside "bridge is up" is how a half-started bridge looked green.
API_JSON="$(curl -s http://127.0.0.1:8700/openapi.json 2>/dev/null || true)"
# ⚠️ THE SNAPSHOT FINGERPRINT IS OVER THE WHOLE APP LAYER, NOT app.py ALONE. It used
# to hash bridge/app.py, which WAS the app layer; since the router/core split
# (2026-08-28) app.py is a 250-line facade that a normal slice never touches, so that
# hash would have printed the same eight characters ship after ship — a "did my code
# actually land" signal that says yes to everything. Sorted so it is reproducible.
SNAP="$(python3 -c '
import hashlib, sys, pathlib
b = pathlib.Path(sys.argv[1]) / "bridge"
h = hashlib.sha1()
for p in sorted(list(b.glob("*.py")) + list(b.glob("core/*.py")) + list(b.glob("routers/*.py"))):
    h.update(p.name.encode()); h.update(p.read_bytes())
print(h.hexdigest()[:8])' "$DST" 2>/dev/null || echo none)"
if [[ -z "$API_JSON" ]]; then
  echo "[ship] bridge is up (fingerprint unavailable (bridge still starting?), snapshot app layer $SNAP)"
else
  MARK="$(printf '%s' "$API_JSON" | python3 -c 'import sys,hashlib; print(hashlib.sha1(sys.stdin.buffer.read()).hexdigest()[:8])' 2>/dev/null || echo none)"
  echo "[ship] bridge is up (api fingerprint $MARK, snapshot app layer $SNAP)"
fi
# ── optional component restarts, RUN FROM THE SNAPSHOT ────────────────────────
# From the snapshot, not the repo: the app's venv is the upgraded one and the repo's
# is a different install. start_component.sh is a full restart by construction (stop
# → listener-scoped port clear → re-seed guards → relaunch), so it does strictly more
# than the panel's Stop/Start buttons.
RESTART_FAILURES=()
if [[ ${#RESTART[@]} -gt 0 ]]; then
  for _c in ${RESTART[@]+"${RESTART[@]}"}; do
    echo "[ship] restarting component '${_c}' FROM THE SNAPSHOT (${DST})"
    if bash "$DST/scripts/start_component.sh" "$_c"; then
      echo "[ship] restarted: ${_c}"
    else
      echo "[ship] WARN: restart of '${_c}' FAILED (output above) — check ${DST}/data/logs/${_c}.log"
      RESTART_FAILURES+=("$_c")
    fi
  done
fi

if [[ ${#RESTART_FAILURES[@]} -gt 0 ]]; then
  echo "[ship] INCOMPLETE: the snapshot/app/bridge were shipped, but requested component restart(s) failed: ${RESTART_FAILURES[*]}"
  echo "[ship] Resolve the named component logs and rerun the exact --restart request."
  exit 1
fi

echo "[ship] REMINDER: components stay up - a vendored upgrade needs: ./scripts/ship.sh --restart <name>"
echo "[ship] done — the served code now matches the repo. ⌘R open tabs if the panel looks stale."
