#!/usr/bin/env bash
# ship.sh — push current repo code into the FAT app snapshot and restart cleanly.
#
# Exists because the fat app serves a provisioned SNAPSHOT (~/Library/Application
# Support/Harness), not the repo, and the bridge is a separate process that can
# outlive the app (quit app ≠ restart bridge). Both traps have burned sessions.
# This script is THE way to ship: run it after any code change, done.
#
#   ./scripts/ship.sh          ship + restart
#
# What it does, in order:
#   1. repo bridge/panel + bridge/*.py + scripts/ + guards/ + policies/ → snapshot
#      (NEVER harness.yaml or data/ — those hold live state)
#   2. if app/main.swift is newer than the installed app binary → recompile the
#      Swift shell in place + ad-hoc re-sign (no full fat rebuild)
#   3. quit the app, kill the :8700 bridge LISTENER (components stay up),
#      relaunch, wait for the bridge, print a sanity check
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DST="$HOME/Library/Application Support/Harness"
APP="/Applications/Harness.app"

[[ -d "$DST" ]] || { echo "[ship] ERROR: no snapshot at $DST (fat app not provisioned?)"; exit 1; }
[[ -d "$APP" ]] || { echo "[ship] ERROR: $APP not found"; exit 1; }

echo "[ship] repo → snapshot (panel, bridge, scripts, guards, policies)"
cp -R "$ROOT/bridge/panel/." "$DST/bridge/panel/"
# EVERY top-level bridge module, not just app.py: app.py now imports sibling modules
# (bridge/voice.py, Phase B) and copying only app.py would ship an app.py whose import
# target does not exist in the snapshot. app.py degrades gracefully if voice.py is
# missing, but the snapshot must simply carry the whole package.
# ⚠️ PENDING FABLE QA — ship.sh is the critical ops path and the manifest-merge note
# in CLAUDE.md makes changes here Fable-lane. This one is minimal and additive (same
# destination dir, no new semantics, subdirectories untouched), and the alternative
# was a bridge that cannot import on the first ship. Flagged, not assumed.
for _m in "$ROOT"/bridge/*.py; do
  cp "$_m" "$DST/bridge/$(basename "$_m")"
done
for d in scripts guards policies; do
  [[ -d "$ROOT/$d" ]] && mkdir -p "$DST/$d" && cp -R "$ROOT/$d/." "$DST/$d/"
done

# Swift shell: recompile only when main.swift is newer than the installed binary.
if [[ "$ROOT/app/main.swift" -nt "$APP/Contents/MacOS/Harness" ]]; then
  echo "[ship] main.swift changed → recompiling the shell"
  if [[ ! -f "$ROOT/app/Config.swift" ]]; then
    cat > "$ROOT/app/Config.swift" <<EOF
// generated by ship.sh — do not edit
let harnessRoot = "$ROOT"
let fatBuild = true
EOF
  fi
  swiftc -O "$ROOT/app/main.swift" "$ROOT/app/Config.swift" -o "$APP/Contents/MacOS/Harness"
  codesign --force --sign - "$APP"
fi

# harness.yaml is NEVER copied wholesale (the snapshot's copy holds LIVE state:
# installed flags, runner.model, aux.model). But a NEW component or build pin added
# in the repo would then never reach the app — its card simply never appears. So:
# ADDITIVE merge only. Existing keys/values in the snapshot are never touched; new
# components arrive as installed:false (install state is per-machine).
# Pick a python that HAS pyyaml. The bridge venv always does; a bare system python3
# often does NOT — and skipping silently there would hide a missing component card
# (exactly the failure this merge exists to prevent), so a miss is loud.
MERGE_PY=""
for _c in "$DST/data/bridge-venv/bin/python" "$ROOT/data/bridge-venv/bin/python" python3; do
  if "$_c" -c "import yaml" >/dev/null 2>&1; then MERGE_PY="$_c"; break; fi
done
if [[ -z "$MERGE_PY" ]]; then
  echo "[ship] WARN: no python with pyyaml found — MANIFEST MERGE SKIPPED."
  echo "[ship]       New components will NOT get a Mission Control card until this is fixed."
else
"$MERGE_PY" - "$ROOT/harness.yaml" "$DST/harness.yaml" <<'PY'
import sys, shutil, datetime, yaml
# CRITICAL: safe_dump writes an EMPTY value as the literal `null`, and the shell
# readers (awk/sed in start_component.sh) then take the 4-char string "null" as a
# real value — e.g. `runner.binary:` (empty = auto-discover) became
# `runner.binary: null` and every model load died with "not executable: null".
# Emit None as a truly empty scalar so an empty key round-trips as an empty key.
yaml.add_representer(type(None),
                     lambda d, _v: d.represent_scalar('tag:yaml.org,2002:null', ''),
                     Dumper=yaml.SafeDumper)
src_p, dst_p = sys.argv[1], sys.argv[2]
try:
    src = yaml.safe_load(open(src_p)) or {}
    dst = yaml.safe_load(open(dst_p)) or {}
except Exception as e:
    print(f"[ship] WARN: could not read a harness.yaml ({e}) — manifest merge skipped")
    sys.exit(0)
added = []
for k, v in src.items():
    if k not in dst:
        dst[k] = v; added.append(k)
for section, force in (("components", True), ("build", False)):
    s, d = src.get(section), dst.get(section)
    if isinstance(s, dict) and isinstance(d, dict):
        for name, cfg in s.items():
            if name not in d:
                if force and isinstance(cfg, dict):
                    cfg = dict(cfg); cfg["installed"] = False; cfg["enabled"] = False
                d[name] = cfg; added.append(f"{section}.{name}")
if added:
    shutil.copy2(dst_p, dst_p + ".bak-" + datetime.datetime.now().strftime("%Y%m%d%H%M%S"))
    # keep only the 5 newest backups (Fable QA: unbounded .bak accumulation)
    import glob, os
    baks = sorted(glob.glob(dst_p + ".bak-*"))
    for old in baks[:-5]:
        try: os.remove(old)
        except OSError: pass
    with open(dst_p, "w") as f:
        yaml.safe_dump(dst, f, sort_keys=False, default_flow_style=False)
    print("[ship] manifest: added " + ", ".join(added) + " (snapshot backed up)")
else:
    print("[ship] manifest: up to date (" + str(len(dst.get("components") or {})) + " components)")
PY
fi

echo "[ship] restarting app + bridge (components stay up)"
pkill -x Harness 2>/dev/null || true
sleep 2
lsof -ti tcp:8700 -sTCP:LISTEN 2>/dev/null | xargs kill -9 2>/dev/null || true
sleep 1
open "$APP"

printf "[ship] waiting for the bridge"
for _ in $(seq 1 30); do
  if curl -sf http://127.0.0.1:8700/status >/dev/null 2>&1 || \
     curl -sf http://127.0.0.1:8700/ >/dev/null 2>&1; then
    break
  fi
  printf "."; sleep 1
done
echo

MARK="$(curl -s http://127.0.0.1:8700/openapi.json | python3 -c 'import sys,hashlib; print(hashlib.sha1(sys.stdin.buffer.read()).hexdigest()[:8])' 2>/dev/null || echo none)"
SNAP="$(python3 -c 'import hashlib; print(hashlib.sha1(open("'"$DST"'/bridge/app.py","rb").read()).hexdigest()[:8])' 2>/dev/null || echo none)"
echo "[ship] bridge is up (api fingerprint $MARK, snapshot app.py $SNAP)"
echo "[ship] done — the served code now matches the repo. ⌘R open tabs if the panel looks stale."
